### ISSUE TITLE
Dashboard \ Activity \ Recent comments shows different avatars

### ISSUE THREAD

**Issue by Jon007** [NoahDragon/cat-generator-avatars#12]
Note that in the WordPress Dashboard, the Recent Comments section of the Activity widget continues to show default Gravatar settings and ignores the Cat Avatars.

**Comment by NoahDragon** [comment]
I noticed this issue, it caused by we removed the http request to Gavatar server.

https://github.com/NoahDragon/cat-generator-avatars/commit/d69e04464f6f1cfde1aae3c415da2ef0f7fdf8ba#diff-989826f3005c739051bd9336445364e5L375

**Comment by Jon007** [comment]
I think it's the opposite of that:  the Wordpress Dashboard ignores the Cat settings and it goes to Gravatar anyway.

I didn't have time to look yet but there is probably another filter there somewhere.

**Comment by NoahDragon** [comment]
You are right. It is the opposite. I will take a look.

**Comment by NoahDragon** [comment]
I don't feel it is a bug now, as other generated avatars also have the same behaviour.
