### ISSUE TITLE
BuddyPress cat-generator-avatars

### ISSUE THREAD

**Issue by Jon007** [NoahDragon/cat-generator-avatars#2]
Great plugin, how about adding the code to allow cat-generator-avatars to work for BuddyPress profiles, which really makes a lot of use of avatars.

#### Version Information

* PHP:  7  
* WordPress: Latest 

#### Steps to Reproduce

1. install BuddyPress

#### What I Expected

BuddyPress profiles could use cat-generator-avatars

#### What Happened Instead

cat-generator avatars show in wp-admin but not on BuddyPress profiles

**Comment by NoahDragon** [comment]
I never did such work before. I will take a look.

**Comment by Jon007** [comment]
I've got the basic code for it actually, maybe I should do a pull request.

**Comment by NoahDragon** [comment]
Great. Please do so.

**Comment by Jon007** [comment]
ok that's done.

Notes/observations:
 - there's effectively some duplicated code as I added new functions for getting the url and the image tag as required by BuddyPress, but I didn't change the original filter_avatar to use the new functions
 - first attempt had issues as the various hooks were not allowing user to upload custom image and were always showing cat avatar even if an image had been uploaded, so various extra checks added for this
 - finally, I also had to change the original filter_avatar to check for user uploaded profile image and disable the gravatar check see #4

**Comment by NoahDragon** [comment]
Published to Wordpress, please have a look.

**Comment by Jon007** [comment]
Looking good so far, thanks, let's close this one!
