### ISSUE TITLE
Crediting original authors

### ISSUE THREAD

**Issue by Jookia** [NoahDragon/cat-generator-avatars#22]
The current readme doesn't mention that the art is CC-BY and that the original code was also derived by David Revoy and the MonsterID code. I think it's mentioned in the PHP file itself for the code parts but it would be best to have it explicitly mentioned. The original README containing full details can be found at https://framagit.org/Deevad/cat-avatar-generator/tree/master which is a good example of doing this.

All that said, awesome derivation!

**Comment by Deevad** [comment]
+1 with @Jookia , awesome derivation!

I totally agree about the license. @NoahDragon you can paste the markdown block under on your README.md to fix it ; and add your name and details about your derivation :
```
## License:

**Artworks:**
PNG and ORA files licensed under: [CC-By 4.0](https://creativecommons.org/licenses/by/4.0/) attribution: David Revoy with the following exception: Generated cats used as Avatar (for blog,forum,social-network) don't need direct attribution and so, can be used as regular avatars without pasting David Revoy's name all over the place.

**Code**
A derivation from the original [MonsterID by Andreas Gohr's](https://www.splitbrain.org/blog/2007-01/20_monsterid_as_gravatar_fallback), PHP licensed under the short, simple and permissive:
[MIT License](https://en.wikipedia.org/wiki/MIT_License)
```

**Comment by NoahDragon** [comment]
Thanks for pointing this out, and thanks for @Deevad awesome artwork. Really love the cats!
