### ISSUE TITLE
Remove Gravatar check

### ISSUE THREAD

**Issue by Jon007** [NoahDragon/cat-generator-avatars#4]
The original purpose of cat-generator-avatar was to replace gravatar:
https://www.peppercarrot.com/article390/my-fight-against-cdn-libraries

However the 1.0 source code includes a validate_gravatar() function which explicitly calls out to gravatar.com which particularly slows down the user listing page (and is also slow or blocked from certain locations such as China).

Since the purpose of cat-generator is to remove gravatar, I propose removing this check.
Instead in my branch I added check for locally uploaded avatar image in case the user has chosen to replace their cat avatar with an uploaded image.

**Comment by NoahDragon** [comment]
Agree.
