### ISSUE TITLE
Ultimate Member support

### ISSUE THREAD

**Issue by Jon007** [NoahDragon/cat-generator-avatars#8]
Hi,

One more release checked in to support Ultimate Member, please would you push to wordpress.org.
I've already pushed it out to a production site using Ultimate Member, it seems to be working fine.

UltimateMember uses it's own directory for user-uploaded pictures so widened the check for uploaded pictures.

Also UltimateMember has high priority hook to override Wordpress Avatar settings with it's own Gravatar settings.  The solution was to increase the priority of the Cat Avatar hook so it takes precedence.

Last change, not planning to do any more, it seems pretty good already!

**Comment by NoahDragon** [comment]
Great. Uploaded.
